import {pointSprite} from './point-sprites.js?v=b0edb1b3bbff';
export function drawTethers(ctx,g,glow){
  for(const bolt of g.chainBolts){ctx.save();ctx.globalAlpha=Math.min(1,bolt.life/.3);ctx.strokeStyle='#ead5af';ctx.lineWidth=1;glow(ctx.strokeStyle,ctx.globalAlpha,1.5);ctx.beginPath();for(let i=0;i<bolt.nodes.length-1;i++){const a=bolt.nodes[i],b=bolt.nodes[i+1],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,nx=-dy/d,ny=dx/d;ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo((a.x+b.x)/2+nx*1.8,(a.y+b.y)/2+ny*1.8,b.x,b.y);ctx.quadraticCurveTo((a.x+b.x)/2-nx*1.8,(a.y+b.y)/2-ny*1.8,a.x,a.y);}ctx.stroke();
    for(const p of [bolt.nodes[0],bolt.nodes.at(-1)]){ctx.fillStyle='#1d1a17';ctx.beginPath();ctx.arc(p.x,p.y,4.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff0c9';ctx.lineWidth=1.3;glow(ctx.strokeStyle,1,2);ctx.stroke();ctx.fillStyle='#fff5de';ctx.fillRect(p.x-.8,p.y-.8,1.6,1.6);}ctx.restore();
  }
  for(const a of g.asteroids){if(a.dead||!a.thruster)continue;const t=a.thruster,x=a.x-t.x*(a.r+5),y=a.y-t.y*(a.r+5);ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(t.x,-t.y));ctx.strokeStyle='#c8edff';ctx.lineWidth=1;glow(ctx.strokeStyle,1,1.8);ctx.fillStyle='#112129';ctx.fillRect(-3,-7,6,12);ctx.strokeRect(-3,-7,6,12);ctx.beginPath();ctx.moveTo(-4,-6);ctx.lineTo(4,-6);ctx.moveTo(-4,5);ctx.lineTo(4,5);ctx.stroke();const flame=12+Math.sin(g.time*35+a.r)*3;ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.4;ctx.drawImage(pointSprite('#69bfff'),-11,3,22,flame+12);ctx.globalAlpha=.9;ctx.strokeStyle='#8cdaff';ctx.lineWidth=2;glow(ctx.strokeStyle,.9,2);ctx.beginPath();ctx.moveTo(-2,5);ctx.lineTo(0,5+flame);ctx.lineTo(2,5);ctx.stroke();ctx.lineWidth=.8;ctx.strokeStyle='#f0ffff';ctx.beginPath();ctx.moveTo(0,5);ctx.lineTo(0,10);ctx.stroke();ctx.restore();}
}
export function drawThrusterMissile(ctx,b,glow){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vx,-b.vy));ctx.strokeStyle='#ccefff';ctx.lineWidth=1;glow(ctx.strokeStyle,1,1.8);ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-3,-1);ctx.lineTo(-3,5);ctx.lineTo(3,5);ctx.lineTo(3,-1);ctx.closePath();ctx.stroke();ctx.strokeStyle='#81d0ff';ctx.lineWidth=1.4;glow(ctx.strokeStyle,1,2);ctx.beginPath();ctx.moveTo(0,5);ctx.lineTo(0,13);ctx.stroke();ctx.restore();}

// A subpixel core with a restrained halo; shimmer never changes aim or physics.
export function drawThrusterSight(ctx,g,scale=1){if(g.weapon!=='thruster'||g.state==='menu')return;const m=g.muzzle,dx=Math.sin(g.aim),dy=-Math.cos(g.aim),tx=Math.abs(dx)<1e-9?Infinity:(dx>0?480-m.x:-m.x)/dx,ty=-m.y/dy,d=Math.max(0,Math.min(tx,ty)),shimmer=.6+.2*Math.sin(g.time*47)+.12*Math.sin(g.time*83);ctx.save();ctx.globalCompositeOperation='lighter';ctx.globalAlpha=shimmer;ctx.strokeStyle='#ff253b';ctx.shadowColor='#ff1730';ctx.shadowBlur=2*scale;ctx.lineWidth=.5/scale;ctx.beginPath();ctx.moveTo(m.x,m.y);ctx.lineTo(m.x+dx*d,m.y+dy*d);ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=shimmer*.7;ctx.setLineDash([1/scale,12/scale]);ctx.lineDashOffset=-g.time*90;ctx.stroke();ctx.restore();}
